### ISSUE TITLE
devicemotion not triggered on iOS

### ISSUE THREAD

**Issue by EM-LilianaIturribarria** [alexgibson/shake.js#50] opened 2019-05-08 18:03 UTC
Hi guys,
looks like the devicemotion event is no longer working on iOS, android devices work fine.

do you know why?

**Comment by alexgibson** [comment] 2019-05-08 18:05
Closing as a duplicate of https://github.com/alexgibson/shake.js/issues/49

**Closed as completed by alexgibson** 2019-05-08 18:05 UTC
